name: stp2glb
channels:
  - https://repo.prefix.dev/adapy-tools
  - conda-forge
dependencies:
  - occt ==7.8.1=*novtk*debug*
  - stepcode ==0.8.2=*debug*
  - ifcopenshell *=*debug*
  - pytest ==7.3.1
  - cmake ==3.29.2
  - numpy
  - cgal-cpp ==5.6.1
  - cli11
  - tinygltf ==2.8.19 # This must be installed in target dir also if you want to compile
  - python ==3.12
  - tbb-devel