[project]
name = "stp2glb"
version = "1.0.0"
description = "A STEP to GLB converter"
channels = ["https://repo.prefix.dev/adapy-tools", "conda-forge"]
platforms = ["win-64", "linux-64"]

[environments]
static = { features=["static"], no-default-feature = true }
static-mingw = { features=["static-mingw"], no-default-feature = true }
conda  = { features=["conda"], no-default-feature = true }

[feature.conda.dependencies]
rattler-build="*"

[dependencies]
c-compiler = "*"
cxx-compiler = "*"
cmake = "==3.30.5"
cli11 = "*"
tinygltf = "==2.8.19"
ninja = "*"
nlohmann_json = "*"
tbb-devel = "*"
cgal-cpp = "==5.6.1"
pytest = "==7.3.1"
python = "3.12.*"

[target.linux-64.dependencies]
occt = { version = "==7.8.1" }

[target.win-64.dependencies]
vs2022_win-64 = "*"
vswhere = "*"
occt = { version = "==7.8.1", build = "*novtk*debug*", channel = "https://repo.prefix.dev/adapy-tools" }
stepcode = { version = "==0.8.2", build = "*debug*" }
ifcopenshell = { version = "*", build = "*debug*" }

[target.win-64.tasks]
build = { cmd=["cmake","-G","Ninja", "--preset", "win-local-release", "--fresh"] }
install = { cmd = ["ninja", "-C", "build/win-local-release", "install"], description = "Install the project" }
test = { cmd = ["ctest"], cwd="build/win-local-release", description = "Run the tests" }

[feature.static.dependencies]
cmake = "==3.30.5"
cli11 = "*"
ninja = "*"
nlohmann_json = "*"

[feature.static.target.linux-64.dependencies]
c-compiler = "*"
cxx-compiler = "*"
freetype = "*"
freeimage = "*"
occt = { version = "==7.8.1", build = "*static*", channel = "https://repo.prefix.dev/adapy-tools" }

[feature.static.target.win-64.dependencies]
vs2022_win-64 = "*"
vswhere = "*"
occt = { version = "==7.8.1", build = "*static*", channel = "https://repo.prefix.dev/adapy-tools" }

[feature.static-mingw.target.win-64.dependencies]
cmake = "==3.30.5"
cli11 = "*"
ninja = "*"
nlohmann_json = "*"
m2w64-sysroot_win-64 = "*"
gcc_win-64 = "13*"
gxx_win-64 = "13*"
ld_impl_win-64 = "*"
#occt = { version = "==7.8.1", build = "*static*", channel = "https://repo.prefix.dev/adapy-tools" }

[feature.static.target.win-64.tasks]
build = { cmd=["cmake","-G","Ninja", "--preset", "win-local-static", "--fresh"] }
install = { cmd = ["ninja", "-C", "build/win-local-static", "install"], description = "Install the project" }

[feature.static.target.linux-64.tasks]
build = { cmd=["cmake","-G","Ninja", "--preset", "linux-local-static", "--fresh"] }
install = { cmd = ["ninja", "-C", "build/linux-local-static", "install"], description = "Install the project" }

[feature.static-mingw.tasks]
build = { cmd=["cmake","-G","Ninja", "--preset", "win-local-static-mingw", "--fresh"] }
install = { cmd = ["ninja", "-C", "build/win-local-static-mingw", "install"], description = "Install the project" }

[feature.conda.target.win-64.tasks]
build = { cmd=["rattler-build", "build", "-r", "recipes/occt-static/recipe.yaml", "-m","recipes/occt-static/conda_build_config-win.yaml"] }
upload = { cmd=["rattler-build", "upload", "-c", "adapy-tools"]}

[feature.conda.target.linux-64.tasks]
build = { cmd=["rattler-build", "build", "-r", "recipes/occt-static/recipe.yaml", "-m","recipes/occt-static/conda_build_config-linux.yaml"] }