[project]
name = "stp2glb"
version = "1.0.0"
description = "A STP to GLB converter"
channels = ["conda-forge"]
platforms = ["win-64"]

[environments]
local-win = ["local-win"]

[feature.local-win]
platforms = ["win-64"]
channels = ["https://repo.prefix.dev/adapy-tools", "conda-forge"]

[feature.local-win.dependencies]
c-compiler = "*"
cxx-compiler = "*"
occt = { version = "7.8.1", build = "*novtk*debug*", channel = "https://repo.prefix.dev/adapy-tools" }
stepcode = { version = "0.8.2", build = "*debug*" }
ifcopenshell = { version = "*", build = "*debug*" }
pytest = "7.3.1"
cmake = "3.29.2"
numpy = "*"
cgal-cpp = "5.6.1"
cli11 = "*"
tinygltf = "2.8.19"
python = "3.12"
tbb-devel = "*"
