name: ci-build-and-release

# bump 1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
#        python: [3.9, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.2
          cache: true

      - name: Build
        run: |
          pixi run -e static build && pixi run -e static install

