name: ci-occt-static-build

# bump 1
on:
  workflow_dispatch:
  push:
    paths:
      - 'recipes/occt-static/**'
      - '.github/workflows/ci-occt-static-build.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          activate-environment: conda
          cache: true

      - name: Build
        run: |
          pixi run -e conda build-occt

      - name: Upload all packages
        shell: pixi run bash -e {0}
        run: |
          shopt -s nullglob
          EXIT_CODE=0
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            if ! rattler-build upload prefix -c adapy-tools "${pkg}"; then
              EXIT_CODE=1
            fi
          done
          exit $EXIT_CODE
